name: test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: npm start lint
